mysite/myapp/urls.py
from django.urls import path
from . import views

app_name='myapp'

urlpatterns = [
    path('',views.index,name="home"),
    # path('products/',views.products,name='products'),
    # path('products/<int:id>/',views.product_detail,name='product_detail'),
    # path('products/add/',views.add_product,name="add_product"),
    # path('products/update/<int:id>/',views.update_product,name="update_product"),
    # path('products/delete/<int:id>/',views.delete_product,name="delete_product"),

    path('products/',views.ProductListView.as_view(),name='products'),
    path('products/<int:pk>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('products/add/',views.ProductCreateView.as_view(),name="add_product"),
    path('products/update/<int:pk>/',views.ProductUpdateView.as_view(),name="update_product"),

    path('products/delete/<int:pk>/',views.ProductDelete.as_view(),name="delete_product"),

    path('products/mylistings/',views.my_listings,name='mylistings'),

### payment:

    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<int:id>',views.create_checkout_session,name='api_checkout_session'),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls'))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.create_profile,name='createprofile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='sellerprofile'),
]

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Product(models.Model):
    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        return reverse('myapp:products')


    seller=models.ForeignKey(to=User,on_delete=models.CASCADE,default=1)
    name=models.CharField(max_length=100)
    price=models.IntegerField()
    desc=models.CharField(max_length=250)
    image=models.ImageField(blank=True,upload_to='images')
    
## for payment gateway

class OrderDetail(models.Model):
    customer_username=models.CharField(max_length=100)
    product = models.ForeignKey(to=Product,on_delete=models.PROTECT)
    price = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid=models.BooleanField(default=False)
    createdon=models.DateTimeField(auto_now_add=True)
    updatedon=models.DateTimeField(auto_now_add=True)

mysite/myapp/views.py
from django.shortcuts import render,redirect
from .models import Product,OrderDetail
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy,reverse
from django.core.paginator import Paginator
from django.db.models import Q
from users.models import Profile
from django.core.exceptions import ValidationError

# FOR PAYMENT GATEWAY

from django.http import JsonResponse
from django.http.response import HttpResponseNotFound,JsonResponse
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import stripe



# Create your views here.
def index(request):
    return render(request,'myapp/myapp.html')

def products(request):
    page_obj = products = Product.objects.all()
    
    product_name=request.GET.get('product_name')

    if product_name!='' and product_name is not None:
        page_obj=products.filter(name__icontains=product_name)


    paginator=Paginator(products,3)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    context={
        'page_obj':page_obj

    }
    return render(request,'myapp/index.html',context)




# class based view

class ProductListView(ListView):

    model=Product
    template_name='myapp/index.html'
    context_object_name='products'
    paginate_by=3

    def get_queryset(self):
        queryset = super().get_queryset()
        product_name = self.request.GET.get('product_name')

        if product_name:
            queryset = queryset.filter(Q(name__icontains=product_name))

        return queryset




def product_detail(request,id):
    product =Product.objects.get(id=id)
    context={
        "product":product
    }
    return render(request,'myapp/detail.html',context)







@login_required
def add_product(request):
    if(request.method=='POST'):
        name=request.POST.get('name')
        price=request.POST.get('price')
        desc=request.POST.get('desc')
        image=request.FILES['upload']
        seller=request.user
        product=Product(name=name,price=price,desc=desc,image=image,seller=seller)
        product.save()
    return render(request,'myapp/addproduct.html')


# class based add view :

class ProductCreateView(CreateView):

    model=Product
    fields=['name','price','desc','image','seller']
    template_name='myapp/productcreate.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not Profile.objects.filter(user=request.user).exists():
            return redirect(reverse_lazy('users:createprofile')) 
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        if not form.cleaned_data['name'] or not form.cleaned_data['price'] or not form.cleaned_data['desc'] or not self.request.FILES.get('image'):
            form.add_error(None, "All fields must be filled out.")
            return self.render_to_response(self.get_context_data(form=form))
        form.instance.seller = self.request.user
        return super().form_valid(form)




@login_required
def update_product(request,id):
    product =Product.objects.get(id=id)
    if(request.method=='POST'):
        product.name=request.POST.get('name')
        product.price=request.POST.get('price')
        product.desc=request.POST.get('desc')
        if 'upload' in request.FILES:
            product.image = request.FILES['upload']
        product.save()
        return redirect(f'/myapp/products/{id}')
    context={
        "product":product
    }
    return render(request,'myapp/updateproduct.html',context)





# class based view for Update view


class ProductUpdateView(UpdateView):

    model=Product
    fields=['name','price','desc','image','seller']
    template_name_suffix='_update_form'


@login_required
def delete_product(request,id):
    product =Product.objects.get(id=id)
    if(request.method=='POST'):
        if 'Delete' in request.POST:
            product.delete()
            return redirect('/myapp/products/')
        elif 'Cancel' in request.POST:
            return redirect('/myapp/products/') 
    context={
        "product":product
    }
    return render(request,'myapp/deleteproduct.html',context)

# class based view for delete:

class ProductDelete(DeleteView):
    model=Product
    template_name_suffix='_confirm_delete'
    success_url=reverse_lazy('myapp:products')


@login_required
def my_listings(request):
    products = Product.objects.filter(seller=request.user)
    context={
        'products':products
    }
    return render(request,'myapp/mylistings.html',context)




### payment through stripe


# class based detailed view:

class ProductDetailView(DetailView):
    model=Product
    template_name='myapp/detail.html'
    context_object_name='product'
    pk_url_kwargs='pk'

    def get_context_data(self, **kwargs):
        context=super(ProductDetailView,self).get_context_data(**kwargs)
        context['stripe_publishable_key']=settings.STRIPE_PUBLISHABLE_KEY
        return context

@csrf_exempt
def create_checkout_session(request, id):
    """
    Create a Stripe checkout session for a product.

    Args:
        request (HttpRequest): The request object.
        id (int): The product ID.

    Returns:
        JsonResponse: A JSON response with the checkout session ID.
    """
    product = get_object_or_404(Product, pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    # Create a Stripe checkout session
    checkout_session = stripe.checkout.Session.create(
        customer_email=request.user.email,
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': product.name,
                    },
                    'unit_amount': int(product.price * 100),  # Convert to cents
                },
                'quantity': 1,
            }
        ],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('myapp:success')) + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse('myapp:failed')),
    )

    # Create an order detail instance
    order = OrderDetail()
    order.customer_username = request.user.username
    order.product = product
    order.stripe_payment_intent = checkout_session['id']
    order.price = int(product.price * 100)  # Convert to cents
    order.save()

    # Return the checkout session ID as a JSON response
    return JsonResponse({'sessionId': checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name='myapp/payment_success.html'

    def get(self, request, *args, **kwargs):
        session_id=request.GET.get('session_id')
        if session_id is None:
            return HttpResponseNotFound()        
        session=stripe.checkout.Session.retrieve(session_id)
        stripe.api_key=settings.STRIPE_SECRET_KEY
        order = get_object_or_404(OrderDetail,stripe_payment_intent=session.id)
        order.has_paid=True
        order.price = int(order.price / 100)
        order.save()
        context = self.get_context_data(**kwargs)
        context['order'] = order

        return self.render_to_response(context)
    
        # return render(request,self.template_name)

class PaymentFailedView(TemplateView):
    template_name='myapp/payment_failed.html'

mysite/myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-2xl font-bold m-10 text-green-500">+ Add Product</h1>

<form class="bg-white text-black shadow-md m-10 px-8 py-9 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Name</label>
            <input class="shadow rounded border appearance-none py-3 px-4 ml-10 text-gray-700" type="text" name="name" id="name" placeholder="product name">
    </div>
    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Price</label>
            <input class="shadow rounded border appearance-none py-3 px-4 ml-10 text-gray-700" type="text" name="price" id="price" placeholder="product price">
    </div>
    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Description</label>
            <input class="shadow rounded border appearance-none py-3 px-4 ml-10 text-gray-700" type="text" name="desc" id="desc" placeholder="product desc">     
    </div>
    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Image</label>
            <input class=" py-3 px-4 ml-10 text-gray-700" type="file" accept="image/*" name="upload" id="upload" >
    </div>
     <div class="mb-5">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add_product" id="Add_product" value="Add Product">
    </div>
</form>

{% endblock %}

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'myapp/styles.css'  %}" />
    <title>Document</title>
  </head>
  <body class="bg-gray-300 text-gray-900 bg-blue-100" > <!-- style="background-color:rgb(226, 226, 226);" -->
    <nav class="br-white shadow-lg" style="background-color:rgba(41,38,45,255);">
      <div class="max-w-6xl  px-4">
        <div>
          <div class="flex space-x-20">
            <div class="ml-0">
              <a class="flex px-2 py-4 items-center" href="{% url 'myapp:home' %}">
                <img class="h-8 w-8 mx-2" src="{% static 'myapp/images/icon.png' %}"/>
                <span class="text-gray-500 text-lg font-semibold block">RUSTEZ`e</span>
              </a>
            </div>
            <div class="flex items-center space-x-1">
              <a
                href="{% url 'myapp:products' %}"
                class="py-4 px-4 text-gray-500 font-semibold border-b-4 border-green-500"
                >Home</a
              >
              <!-- <a href="{% url 'myapp:products' %}" class="py-4 px-4 text-gray-500 font-semibold"
                >View product</a
              > -->
              </div>
              <div class='flex items-center space-x-1'>
              {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}" class="py-4 px-5 text-gray-500 font-semibold">Profile</a>
                <a href="{% url 'users:logout' %}" class="py-4  px-5 text-gray-500 font-semibold">Logout</a>
                <a href="{% url 'myapp:mylistings' %}" class="py-4 px-5 text-gray-500 font-semibold">My products</a>
                <a href="{% url 'myapp:add_product' %}" class="py-4 px-4 text-gray-500 font-semibold">Add product</a>
              {% else %}
                <a href="{% url 'users:login' %}" class="py-4 px-20 text-gray-500 font-semibold">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
  </body>
</html>

mysite/myapp/templates/myapp/deleteproduct.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1  class="text-2xl font-bold m-10 text-red-500">Delete Product</h1>
<form class="bg-white text-black shadow-md m-10 px-8 py-9 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-5">
        <label class="block text-lg font-bold mb-2">Confirm To Delete the Product</label>
    </div>
    <div class="mb-5">
        <label  class="block text-sm mb-2"> <b>Product Name :</b> {{product.name}}</label>
    </div>

    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Image</label>
        <img src="{{product.image.url}}" class="w-20 h-20">
    </div>
     <div class="mb-5">
        <input class="rounded bg-red-500 text-white px-5 py-2 mr-6" type="submit" name="Delete" id="Delete" value="Delete Product">
        <input class="rounded bg-green-500 text-white px-5 py-2" type="submit" name="Cancel" id="Cancel" value="Retain Product">
    </div>
</form>
{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends  "myapp/base.html" %}
{% block content %}
<div class="flex p-10 w-full h-200 items-center">
    <img class="w-1/2"src="{{product.image.url}}" alt="">
    <div class="w-2/3 text-xl ml-10 mt-10">
        <div class="mt-5">{{product.name}}</div>
        <div class="mt-5 text-green-500">$ {{product.price}}</div>
        <div class="mt-5 text-gray-700">{{product.desc}}</div>

        <div class="mt-5 text-black"> Posted By : 
            <a href="{% url 'users:sellerprofile' product.seller.id %}" class="text-blue-500">
            {{product.seller}}</a>
        </div>
        <div class="mt-5 text-black flex">Contact : <p class="text-blue-500">{{product.seller.profile.contact_number}}</p>

        </div>
    <div>
        <button class="rounded bg-green-500 text-white px-3 py-2 mt-2" id="checkout">Checkout</button>
    </div>
    </div>
</div> 
    <script src="https://js.stripe.com/v3/"></script>
        <script type="text/javascript">

            var stripe=Stripe('{{stripe_publishable_key}}')
            var checkoutButton=document.getElementById('checkout')
            checkoutButton.addEventListener('click',function(){  
                fetch("{% url 'myapp:api_checkout_session' id=product.id %}",{method:'POST',})
                .then(function(response){
                    return response.json()
                })
                .then(function(session){
                    return stripe.redirectToCheckout({sessionId:session.sessionId})
                })
                .then(function(result){
                    if(result.error){
                        alert(result.error.message)
                    }   
                })
                .catch(function(error){
                    console.error('Error',error)
                })
                
            })
        </script>

 
        
    


{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html'%} {% load static %} {% block content %}

<!-- site hero starts here -->
<main
  class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-20"
>
  <div class="sm:text-center lg:text-left">
    <div class="text-4xl text-gray-900 font-extrabold sm:text-5xl md:6xl flex items-baseline">
      <span class="block xl:inline"> Premium products</span>
      <span class="block xl:inline"><img class="h-8 w-8 mx-2" src="{% static 'myapp/images/cart.png' %}"/></span>
      <span class="block text-blue-500 xl:inline"> Modest Pricing </span>
    </div>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:5 md:text-xl lg:mx-0">
      Get the best quality products acroos the world.Free Shipping
    </p>
  </div>
</main>
<!-- site hero ends here -->

<div class="flex mt-5 p-10 justify-center">
  <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
</div>

<div class="mt-5 p-10 justify-center">
  <label>
    <h2 class="text-xl font-normal mt-0 mb-2 text-gray">
      Search Products
    </h2>
  </label>
  <form method="get">
    <input class="text-lg text-black w-96 h-10 rounded px-2" type="text" name="product_name" id="product_name" placeholder="Type to search products">
  </form>
</div>



<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
  <!-- card1 -->
  {% for product in products %}   <!-- for pagination in function view change this 'products' as 'page_obj' -->
  <a href="{% url 'myapp:product_detail' product.id %}">
  <div class="rounded overflow-hidden shadow-lg bg-white">
    <img class="w-full" src="{{product.image.url}}" alt="" />
    <div class="px-6 py-4">
      <div class="font-bold text-xl mb-2">{{product.name}}</div>
      <div class="font-bold text-xl text-green-500 mb-2">
        $ {{product.price}}
      </div>
      <div class="font-bold text-xl mb-2 text-black">Posted By : <span class="text-indigo-500">{{product.seller}}</span></div>
      <p class="text-gray-700 text-base">{{product.desc}}</p>
    </div>
  </div>
 </a>
  {% endfor %}
</div>
<!-- pagination code starts -->
<div class="pagination flex justify-center items-center mb-20 mt-10">
  <span>
    <a href="?page=1" class="text-sm font-bold border py-2 px-4 items-center inline-flex relative text-black border-black z10" >First</a>
    {% if page_obj.has_previous %}
      <a href="?page={{page_obj.previous_page_number}}" class="text-sm font-bold border py-2 px-4 items-center inline-flex relative text-black border-black z10">Previous</a>
    {% endif %} 
    <span class="text-sm font-bold border py-2 px-4 items-center inline-flex relative text-black border-black z10">
      page {{page_obj.number}} of {{page_obj.paginator.num_pages}} 
    </span>
    
    {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}" class="text-sm font-bold border py-2 px-4 items-center inline-flex relative text-black border-black z10">Next</a>
    {% endif %}
    <a href="?page={{page_obj.paginator.num_pages}}" class="text-sm font-bold border py-2 px-4 items-center inline-flex relative text-black border-black z10">Last</a>
  </span>
</div>


<!-- pagination code ends -->
<nav></nav>





{% endblock %}

mysite/myapp/templates/myapp/myapp.html
{% extends 'myapp/base.html' %} 
{% load static %}

{% block content %}


<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-20">
  <div class="sm:text-center lg:text-left">
    <h1 class=" flex text-4xl text-indigo-900 font-extrabold sm:text-5xl md:6xl">
      <img class="h-20 w-20 mx-2" src="{% static 'myapp/images/icon.png' %}"/>
      <span class="block xl:inline"> Welcome to RUSTEZ`e </span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:5 md:text-xl">
      Your one-stop shop for all your buying and selling needs
    </p>
  </div>
  </main>
  <div class="sm:text-center lg:text-left mx-60 my-20 shadow-lg border p-5 rounded">
    <h1 class=" flex text-indigo-900 text-3xl">
      <img class="h-10 w-10 mx-2" src="{% static 'myapp/images/icon.png' %}"/>
      <span class="block xl:inline"> About us </span>
    </h1>
    <p class="mt-3 text-base text-black mt-5">
      At RUSTEZ`e, we provide a wide variety of products, including electronics, fashion, home goods, and beauty items. 
      Every product is carefully checked to ensure high quality. We use top-notch security to keep your personal information safe. 
      Our reliable shipping partners ensure your order arrives quickly and securely. 
      Plus, our friendly customer service team is always ready to help with any questions or issues you may have, 
      making your shopping experience easy and pleasant.
    </p>
  </div>


{% endblock %}

mysite/myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}


{% block content %}

<div class="flex mt-5 p-10 justify-center">
  <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">MY PRODUCTS</h2>
</div>

<div class="p-10  gap-5">

  {% for product in products %}
  <div class="rounded overflow-hidden shadow-lg flex m-10 bg-white">
    <span class="w-1/3">
        <img class="w-full" src="{{product.image.url}}" alt="" />
    </span>
    <div class="px-6 py-4 w-2/3">
      <div class="font-bold text-xl mb-2">
        {{product.name}}
      </div>
      <div class="font-bold text-xl text-green-500 mb-2">
        $ {{product.price}}
      </div>
      <p class="text-gray-700 text-base">{{product.desc}}</p>
    </div>
    <div class="my-20 w-1/6">
        <a href="{% url 'myapp:update_product' product.id %}" class="rounded bg-green-500 text-white px-5 py-2">Edit</a>
    </div>
    <div class="my-20 w-1/6 item-center">
        <a href="{% url 'myapp:delete_product' product.id %}" class="rounded bg-red-500 text-white px-5 py-2 my-6">Delete</a>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

mysite/myapp/templates/myapp/payment_failed.html
{% extends 'myapp/base.html'%}

{% block content %}

<p>Order UnSuccessfull</p>
<h2>TRy again later</h2>

{% endblock %}

mysite/myapp/templates/myapp/payment_success.html
{% extends 'myapp/base.html'%}

{% block content %}

    <style>
   .card {
        background-color: #fff;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        width: 50%;
        margin: 40px auto;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

   .card-header {
        background-color: #f0f0f0;
        padding: 10px;
        border-bottom: 1px solid #ddd;
    }

   .card-body {
        padding: 20px;
    }

   .card-body ul {
        list-style: none;
        padding: 0;
        margin: 0;
    }

   .card-body li {
        padding: 10px;
        border-bottom: 1px solid #ddd;
    }

   .card-body li:last-child {
        border-bottom: none;
    }
</style>

<div class="card">
    <div class="card-header">
        <h2>Payment Successful!</h2>
    </div>
    <div class="card-body">
        <ul>
            <li>Order ID      : {{ order.id }}</li>
            <li>User Ordered  : {{ order.customer_username }}</li>
            <li>Order Product : {{ order.product }}</li>
            <li>Order Price   : $ {{ order.price }}</li>
            <li>Order Payment : {{ order.has_paid }}</li>
            <li>Payment Intent: {{ order.stripe_payment_intent }}</li>
        </ul>
        <p>Thank you for your payment! Your order has been successfully processed.</p>
    </div>
    <p>Continue shopping <a class="text-blue-700" href="{%  url 'myapp:products' %}">here</a>.</p>
</div>



{% endblock %}

mysite/myapp/templates/myapp/product_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1  class="text-2xl font-bold m-10 text-red-500">Delete Product</h1>
<form class="bg-white text-black shadow-md m-10 px-8 py-9 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-5">
        <label class="block text-lg font-bold mb-2">Confirm To Delete the Product</label>
    </div>
    <div class="mb-5">
        <label  class="block text-sm mb-2"> <b>Product Name :</b> {{product.name}}</label>
    </div>

    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Image</label>
        <img src="{{product.image.url}}" class="w-20 h-20">
    </div>
     <div class="mb-5">
        <input class="rounded bg-red-500 text-white px-5 py-2 mr-6" type="submit" name="Delete" id="Delete" value="Delete Product">
        <!-- <input class="rounded bg-green-500 text-white px-5 py-2" type="submit" name="Cancel" id="Cancel" value="Retain Product"> -->
    </div>
</form>
{% endblock %}

mysite/myapp/templates/myapp/product_update_form.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-2xl font-bold m-10 text-green-500">+ Update Product</h1>

<form class="bg-white text-black shadow-md m-10 px-8 py-9 w-3/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Name</label>
            
            <div class="shadow rounded border appearance-none py-3 px-4 ml-10 text-gray-700 w-1/4">
                {{ form.name }}
            </div>
    </div>
    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Price</label>
             <div class="shadow rounded border appearance-none py-3 px-5 ml-10 text-gray-700 w-1/4">
                {{ form.price }}
            </div>
    </div>
    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Description</label>
           <div class="shadow rounded border appearance-none py-3 px-4 ml-10 text-gray-700 w-1/4">
                {{ form.desc }}
            </div>
    
    </div>

    <div class="mb-5">
        <label class="block text-sm font-bold mb-2">Product Image</label>
             <div class="appearance-none py-3 px-4 ml-10 text-gray-700 w-1/4">
                {{ form.image }}
            </div>
    </div>
    <div class="mb-5 hidden">
        <label class="block text-sm font-bold mb-2">Seller Name</label>
             <div class="appearance-none py-3 px-4 ml-10 text-gray-700 w-1/4">
                {{ form.seller }}
            </div>
    </div>
     <div class="mb-5">
        <input class="bg-green-500 text-white px-5 py-2" type="submit" name="Add_product" id="Add_product" value="Update Product">
    </div>
</form>

{% endblock %}