mysite/myapp/urls.py
from django.urls import path
from . import views

app_name='myapp'

urlpatterns = [
    path('',views.index,name="home"),
    # path('products/',views.products,name='products'),
    # path('products/<int:id>/',views.product_detail,name='product_detail'),
    # path('products/add/',views.add_product,name="add_product"),
    # path('products/update/<int:id>/',views.update_product,name="update_product"),
    # path('products/delete/<int:id>/',views.delete_product,name="delete_product"),

    path('products/',views.ProductListView.as_view(),name='products'),
    path('products/<int:pk>/',views.ProductDetailView.as_view(),name='product_detail'),
    path('products/add/',views.ProductCreateView.as_view(),name="add_product"),
    path('products/update/<int:pk>/',views.ProductUpdateView.as_view(),name="update_product"),

    path('products/delete/<int:pk>/',views.ProductDelete.as_view(),name="delete_product"),

    path('products/mylistings/',views.my_listings,name='mylistings'),

### payment:

    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<int:id>',views.create_checkout_session,name='api_checkout_session'),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls'))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name='users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.create_profile,name='createprofile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='sellerprofile'),
]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(to=User,on_delete=models.CASCADE)
    image=models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    contact_number=models.CharField(max_length=50)
    

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email=forms.EmailField(required=True,widget=forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'demo@gmail.com'}))
    username=forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'focus:outline-none','placeholder':'Admin'}))
    password1=forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))
    password2=forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'focus:outline-none'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    

mysite/users/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from .models import Profile
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


def register(request):

    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            messages.success(request, "Registration successful.")
            return redirect(reverse_lazy('users:login'))
    else:
        form = NewUserForm()
    
    context = {
        'form': form
    }
    return render(request, 'users/register.html', context)


def logout_view(request):

    logout(request)
    return render(request,'users/logout.html')


@login_required
def profile(request):
    return render(request,'users/profile.html')


def create_profile(request):
    try:
        if request.method == 'POST':
            contact_number=request.POST.get('contact_number')
            image=request.FILES['upload']
            user=request.user
            if Profile.objects.filter(user=user).exists():
                profile=Profile.objects.get(user=user)
            else:
                profile=Profile(user=user,image=image,contact_number=contact_number)
                profile.save()
            return redirect(reverse_lazy('myapp:add_product'))
        return render(request,'users/createprofile.html')
    except:
        return redirect(reverse_lazy('myapp:add_product'))


def seller_profile(request,id):
    seller=User.objects.get(id=id)
    context={
        'seller':seller
    }
    return render(request,'users/sellerprofile.html',context)

mysite/users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}


{% block content %}
<form action="" class="bg-white rounded text-black shadow-md m-10 px-8 py-9 w-2/5" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-5">
        <h2 class="block text-lg mb-4">!! Create Seller_Profile To Sell Products !!</h2>
    </div>
    <div class="mb-5">
        <label class="block text-lg font-bold mb-4">Upload Profile Image</label>
        <input placeholder="upload image :" type="file" accept="image/*" name="upload" id="upload" class="w-1/4 py-3 px-4 ml-10 text-gray-700">
    </div>
    <div class="mb-5">
        <label class="block text-lg font-bold mb-4">Upload Contact Number</label>
        <input type="text" placeholder="9999999999" name="contact_number" id="contact_number" class="shadow border rounded appearance-none py-3 px-4 ml-10 text-gray-700 w-1/3 ">
    </div>
    <input type="submit" value="Add" class="bg-green-500 text-white px-5 py-2 ml-10 mt-10 rounded">
</form>

{% endblock %}

mysite/users/templates/users/login.html
{% extends 'myapp/base.html' %}


{% block content %}

<h1 class="text-2xl m-10 font-bold text-black">LOG IN</h1>
<div class="container py-5 px-10">
    <form method="post" class="bg-white rounded text-black shadow-md m-10 px-8 py-9 w-2/5">
        {% csrf_token %}
        <div class="mb-5">
            <label class="block text-sm font-bold mb-4">Username</label>
            <div class="appearance-none shadow border rounded py-3 px-4 ml-10 text-gray-700 w-1/2">
                {{ form.username }}
            </div>
        </div>
        <div class="mb-5">
            <label class="block text-sm font-bold mb-4">Password</label>
            <div class="shadow border rounded appearance-none py-3 px-4 ml-10 text-gray-700 w-1/2">
                {{ form.password }}
            </div>
        </div>
        <div class="mb-5">
            <input class="bg-green-500 text-white px-5 py-2 ml-10 mt-10 rounded" type="submit" name="login" id="login" value="Login">
            <a href="{% url 'users:register' %}" class="text-indigo-500 px-5 py-2 mt-10" >New Account Register Here</a>
        </div>
    </form>
</div>


{% endblock %}

mysite/users/templates/users/logout.html
{% extends 'myapp/base.html' %}


{% block content %}
<div class="flex justify-center">
    <div class="m-10">
        <h1>YOU HAVE BEEN LOGGED OUT</h1>
        <a href="{% url 'users:login' %} " class="text-blue-500">click here to log in</a>
    </div>
</div>


{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'myapp/base.html' %}

<!--  -->

{% block content %}

<div class="p-10">
  <div class="rounded shadow-lg bg-white flex w-2/3">
    <div class="h-full w-1/3">
      <img src="{{user.profile.image.url}}"/>
    </div>
    <div>
      <div class="font-bold text-xl mb-3 px-6 py-2">
        <h1>Name  :  {{user.username}}</h1>
      </div>
    <div class="font-bold text-xl mb-3 px-6 py-2">
        {% if user.profile.contact_number %}
            <h1>Ph No: {{ user.profile.contact_number }}</h1>
        {% else %}
            <p class="text-lg font-normal">No more Details Shown by user</p>
        {% endif %}

    </div>
    </div>
  </div>
</div>

{% endblock %}

mysite/users/templates/users/register.html
{% extends 'myapp/base.html' %}


{% block content %}

<h1 class="text-2xl m-10 font-bold text-black">Register User</h1>
<div class="container py-5 px-10">
    <form method="post" class="bg-white rounded text-black shadow-md m-10 px-8 py-9 w-2/5">
        {% csrf_token %}
        <div class="mb-5">
            <label class="block text-sm font-bold mb-2">Username</label>
            <div class="appearance-none shadow border rounded py-3 px-4 ml-10 text-gray-700 w-1/2">
                {{ form.username }}
            </div>
        </div>
        <div class="mb-5">
            <label class="block text-sm font-bold mb-2">Email</label>
            <div class="shadow border rounded appearance-none py-3 px-4 ml-10 text-gray-700 w-1/2 ">
                {{ form.email }}
            </div>
        </div>
        <div class="mb-5">
            <label class="block text-sm font-bold mb-2">Password</label>
            <div class="shadow border rounded appearance-none py-3 px-4 ml-10 text-gray-700 w-1/2 ">
                {{ form.password1 }}
            </div>
        </div>
        <div class="mb-5">
            <label class="block text-sm font-bold mb-2">Confirm Password </label>
            <div class="shadow border rounded appearance-none py-3 px-4 ml-10 text-gray-700 w-1/2 ">
                {{ form.password2 }}
            </div>
        </div>
        <div class="mb-5">
        <input class="bg-green-500 text-white px-5 py-2 ml-10 rounded" type="submit" name="create user" id="create user" value="Register">
    </div>
    <div class="mb-5">
        <span>Already Have An Account?</span>
        <a href="{% url 'users:login' %}" class="text-indigo-500 py-2" >Login</a>
    </div>
    </form>
</div>


{% endblock %}

mysite/users/templates/users/sellerprofile.html
{% extends 'myapp/base.html' %} 

{% block content %}


<div class="grid p-10 grid-cols-1 md:grid-cols-3 sm:grid-cols-1">
  <div class="rounded shadow-lg">
    <div><img src="{{seller.profile.image.url}}" alt="" /></div>
    <div class="font-bold text-xl mb-3 px-6 py-2">
      <h1>Name  :  {{seller.username}}</h1>
    </div>
    <div class="font-bold text-xl mb-3 px-6 py-2">
      <h1>Ph No :  {{seller.profile.contact_number}}</h1>
    </div>
  </div>
</div>


{% endblock %}